/**
 * The source of `appsync/dynamodb-filter.ts`. It runs in APPSYNC_JS, which has no recursion, no `while` or C-style `for`, no `continue`,
 * no `throw`, no `++`, no `in` operator and no function arguments. The filter tree is therefore folded in two passes over a flat list:
 * `for…of` over a list the loop appends to, then a reverse pass that joins each node's finished children.
 */
export const DYNAMODB_FILTER_SOURCE = `/**
 * Generated by gqlbase: do not edit.
 *
 * Turns a gqlbase filter input into a DynamoDB filter for APPSYNC_JS resolvers. Unlike
 * \`util.transform.toDynamoDBFilterExpression\`, it handles a nested \`where\` on object fields.
 *
 * @example
 * export function request(ctx) {
 *   return { operation: "Scan", filter: toDynamoDBFilter(ctx.args.filter) };
 * }
 */
import { util } from "@aws-appsync/utils";

type Filter = Record<string, unknown>;

export interface DynamoDBFilter {
  expression: string;
  expressionNames: Record<string, string>;
  expressionValues: Record<string, unknown>;
}

interface FilterNode {
  /** \`all\` joins its parts with AND, \`any\` with OR, \`not\` negates its single part. */
  kind: "all" | "any" | "not";
  /** Index of the parent node, -1 for the root. */
  parent: number;
  /** Attribute path of the object the filter applies to, "" at the top. */
  path: string;
  /** The filter object to explode, or null for an \`and\`/\`or\`/\`not\` group. */
  filter: Filter | null;
  /** Finished clauses: leaves first, then each child's expression. */
  parts: string[];
}

interface Placeholders {
  names: Record<string, string>;
  keys: Record<string, string>;
  values: Record<string, unknown>;
  nameCount: number;
  valueCount: number;
}

const COMPARISONS: Record<string, string> = {
  eq: "=",
  neq: "<>",
  lt: "<",
  lte: "<=",
  gt: ">",
  gte: ">=",
};

function nameOf(placeholders: Placeholders, attribute: string): string {
  if (!Object.hasOwn(placeholders.keys, attribute)) {
    const key = \`#n\${placeholders.nameCount}\`;
    placeholders.keys[attribute] = key;
    placeholders.names[key] = attribute;
    placeholders.nameCount += 1;
  }

  return placeholders.keys[attribute];
}

function valueOf(placeholders: Placeholders, value: unknown): string {
  const key = \`:v\${placeholders.valueCount}\`;
  placeholders.values[key] = value;
  placeholders.valueCount += 1;
  return key;
}

function clauseOf(placeholders: Placeholders, path: string, operator: string, operand: unknown): string {
  if (Object.hasOwn(COMPARISONS, operator)) {
    return \`\${path} \${COMPARISONS[operator]} \${valueOf(placeholders, operand)}\`;
  }

  if (operator === "in") {
    const keys: string[] = [];

    for (const item of operand as unknown[]) {
      keys.push(valueOf(placeholders, item));
    }

    if (keys.length === 0) {
      util.error("Filter operator in needs at least one value", "FilterError");
    }

    return \`\${path} IN (\${keys.join(", ")})\`;
  }

  if (operator === "between") {
    const range = operand as unknown[];
    return \`(\${path} BETWEEN \${valueOf(placeholders, range[0])} AND \${valueOf(placeholders, range[1])})\`;
  }

  if (operator === "beginsWith") {
    return \`begins_with(\${path}, \${valueOf(placeholders, operand)})\`;
  }

  if (operator === "contains") {
    return \`contains(\${path}, \${valueOf(placeholders, operand)})\`;
  }

  // \`exists: false\` matches a missing or null value, as in every backend.
  if (operator === "exists") {
    const nullType = valueOf(placeholders, "NULL");

    return operand
      ? \`(attribute_exists(\${path}) AND NOT attribute_type(\${path}, \${nullType}))\`
      : \`(attribute_not_exists(\${path}) OR attribute_type(\${path}, \${nullType}))\`;
  }

  if (operator === "endsWith") {
    util.error("Filter operator endsWith is not supported by DynamoDB", "FilterError");
  }

  return util.error(\`Unknown filter operator \${operator}\`, "FilterError");
}

export function toDynamoDBFilter(filter: Filter | null | undefined): DynamoDBFilter | null {
  if (!filter) {
    return null;
  }

  const placeholders: Placeholders = {
    names: {},
    keys: {},
    values: {},
    nameCount: 0,
    valueCount: 0,
  };

  const nodes: FilterNode[] = [{ kind: "all", parent: -1, path: "", filter, parts: [] }];
  let index = 0;

  // Explode: the loop also visits the nodes it appends, so every level is reached without recursion.
  for (const node of nodes) {
    const current = node.filter ?? {};

    for (const key of Object.keys(current)) {
      const value = current[key];

      if (value === null || value === undefined) {
        // Omitted.
      } else if (key === "and" || key === "or") {
        nodes.push({ kind: key === "and" ? "all" : "any", parent: index, path: node.path, filter: null, parts: [] });
        const group = nodes.length - 1;

        for (const item of value as Filter[]) {
          nodes.push({ kind: "all", parent: group, path: node.path, filter: item, parts: [] });
        }
      } else if (key === "not") {
        nodes.push({ kind: "not", parent: index, path: node.path, filter: null, parts: [] });
        nodes.push({ kind: "all", parent: nodes.length - 1, path: node.path, filter: value as Filter, parts: [] });
      } else {
        const name = nameOf(placeholders, key);
        const path = node.path ? \`\${node.path}.\${name}\` : name;
        const conditions = value as Filter;

        for (const operator of Object.keys(conditions)) {
          const operand = conditions[operator];

          if (operand === null || operand === undefined) {
            // Omitted.
          } else if (operator === "where") {
            nodes.push({ kind: "all", parent: index, path, filter: operand as Filter, parts: [] });
          } else {
            node.parts.push(clauseOf(placeholders, path, operator, operand));
          }
        }
      }
    }

    index += 1;
  }

  // Assemble: children always come after their parent, so walking backwards finishes every child first.
  let expression = "";

  for (const node of nodes.slice().reverse()) {
    let joined = "";

    if (node.kind === "not") {
      joined = node.parts.length ? \`NOT (\${node.parts[0]})\` : "";
    } else if (node.parts.length === 1) {
      joined = node.parts[0];
    } else if (node.parts.length > 1) {
      joined = \`(\${node.parts.join(node.kind === "any" ? " OR " : " AND ")})\`;
    }

    if (joined && node.parent >= 0) {
      nodes[node.parent].parts.push(joined);
    } else if (joined) {
      expression = joined;
    }
  }

  if (!expression) {
    return null;
  }

  return {
    expression,
    expressionNames: placeholders.names,
    expressionValues: util.dynamodb.toMapValues(placeholders.values),
  };
}
`;
