/**
 * The source of `appsync/dynamodb-filter.ts`. It runs in APPSYNC_JS, which has no recursion, no `while` or C-style `for`, no `continue`,
 * no `throw`, no `++` and no function arguments, and whose `for…of` does not visit elements appended during the loop. So the filter is
 * not walked as a tree: one pass over the characters of its JSON renames the operators and drops what DynamoDB cannot take.
 */
export const DYNAMODB_FILTER_SOURCE = `/**
 * Generated by gqlbase: do not edit.
 *
 * Turns a gqlbase filter input into a DynamoDB filter for APPSYNC_JS resolvers, through
 * \`util.transform.toDynamoDBFilterExpression\`:
 * - operators are renamed to AppSync's: \`neq\` → \`ne\`, \`lte\` → \`le\`, \`gte\` → \`ge\`, \`exists\` → \`attributeExists\`;
 * - nested \`where\` conditions on object fields are dropped: AppSync cannot filter on nested paths;
 * - explicit \`null\`s, and conditions left empty, are dropped;
 * - \`endsWith\` is rejected with \`util.error\`.
 *
 * @example
 * export function request(ctx) {
 *   return { operation: "Scan", filter: toDynamoDBFilter(ctx.args.filter) };
 * }
 */
import { util } from "@aws-appsync/utils";

const OPERATORS: Record<string, string> = {
  neq: "ne",
  lte: "le",
  gte: "ge",
  exists: "attributeExists",
};

/**
 * \`filter\` is a filter object (fields, \`and\`, \`or\`, \`not\`), \`filters\` the list under \`and\`/\`or\`,
 * \`condition\` the operators of one field, \`value\` an operand.
 */
interface Level {
  kind: "filter" | "filters" | "condition" | "value";
  /** The last key read in this object. */
  key: string;
  /** Where the current member starts in the output, its leading comma included. */
  member: number;
}

/**
 * Rewrites the JSON of a filter in one pass, keeping a stack of the objects it is in.
 */
function sanitize(json: string): string {
  const levels: Level[] = [];
  let out = "";
  let literal = "";
  let pending = "";
  let inString = false;
  let escaped = false;
  let skipping = false;
  let skipDepth = 0;
  let skipString = false;
  let skipEscaped = false;

  for (const char of json.split("")) {
    let structural = true;

    if (skipping) {
      // Inside a dropped where value: find where it ends, then handle the next character as usual.
      structural = false;

      if (skipString) {
        if (skipEscaped) {
          skipEscaped = false;
        } else if (char === "\\\\") {
          skipEscaped = true;
        } else if (char === '"') {
          skipString = false;
        }
      } else if (char === '"') {
        skipString = true;
      } else if (char === "{" || char === "[") {
        skipDepth += 1;
      } else if ((char === "}" || char === "]") && skipDepth > 0) {
        skipDepth -= 1;
      } else if (skipDepth === 0 && (char === "," || char === "}")) {
        skipping = false;
        structural = true;
      }
    } else if (inString) {
      structural = false;
      literal += char;

      if (escaped) {
        escaped = false;
      } else if (char === "\\\\") {
        escaped = true;
      } else if (char === '"') {
        inString = false;
        pending = literal;
        literal = "";
      }
    } else if (pending) {
      // A string followed by ":" is a key.
      const level = levels[levels.length - 1];

      if (char === ":") {
        structural = false;
        const key = JSON.parse(pending) as string;
        pending = "";
        level.key = key;

        if (level.kind === "condition" && key === "where") {
          out = out.slice(0, level.member);
          skipping = true;
          skipDepth = 0;
        } else if (level.kind === "condition" && key === "endsWith") {
          util.error("Filter operator endsWith is not supported by DynamoDB", "FilterError");
        } else {
          const name = level.kind === "condition" && Object.hasOwn(OPERATORS, key) ? OPERATORS[key] : key;
          out += \`\${JSON.stringify(name)}:\`;
        }
      } else {
        out += pending;
        pending = "";
      }
    }

    if (structural) {
      const level = levels[levels.length - 1];

      if (char === '"') {
        inString = true;
        literal = char;
      } else if (char === "{" || char === "[") {
        let kind: Level["kind"] = "value";

        if (!level) {
          kind = "filter";
        } else if (level.kind === "filter" && char === "[" && (level.key === "and" || level.key === "or")) {
          kind = "filters";
        } else if (level.kind === "filter" && char === "{") {
          kind = level.key === "not" ? "filter" : "condition";
        } else if (level.kind === "filters" && char === "{") {
          kind = "filter";
        }

        out += char;
        levels.push({ kind, key: "", member: out.length });
      } else if (char === "," || char === "}" || char === "]") {
        // A member whose value is null is dropped.
        if (char !== "]" && out.slice(-5) === ":null") {
          out = out.slice(0, level.member);
        }

        if (char === ",") {
          // After a dropped first member, the comma has nothing before it.
          if (out.slice(-1) !== "{" && out.slice(-1) !== "[") {
            level.member = out.length;
            out += char;
          }
        } else {
          const empty = out.slice(-1) === (char === "}" ? "{" : "[");
          out += char;
          levels.pop();
          const parent = levels[levels.length - 1];

          // An object left empty drops the member that holds it.
          if (empty && char === "}" && parent && (parent.kind === "filter" || parent.kind === "condition")) {
            out = out.slice(0, parent.member);
          }
        }
      } else {
        out += char;
      }
    }
  }

  return out;
}

export function toDynamoDBFilter(filter: Record<string, unknown> | null | undefined): unknown {
  if (!filter) {
    return null;
  }

  const sanitized = sanitize(JSON.stringify(filter));

  if (sanitized === "{}" || sanitized === "") {
    return null;
  }

  return JSON.parse(util.transform.toDynamoDBFilterExpression(JSON.parse(sanitized)));
}
`;
