import ts from "typescript";

export const createFileHeaders = (): ts.Node[] => {
  const noticeLine = ts.factory.createIdentifier("\n");
  const checksLine = ts.factory.createIdentifier("\n");

  ts.addSyntheticLeadingComment(
    noticeLine,
    ts.SyntaxKind.MultiLineCommentTrivia,
    ` !!! This is code generated by gqlbase. Do not edit directly. !!! `,
    true
  );

  ts.addSyntheticLeadingComment(
    checksLine,
    ts.SyntaxKind.MultiLineCommentTrivia,
    " eslint-disable ",
    true
  );

  ts.addSyntheticLeadingComment(
    checksLine,
    ts.SyntaxKind.SingleLineCommentTrivia,
    " biome-ignore-all lint: generated file",
    true
  );

  ts.addSyntheticLeadingComment(
    checksLine,
    ts.SyntaxKind.SingleLineCommentTrivia,
    " @ts-nocheck",
    true
  );

  return [noticeLine, checksLine];
};
