export interface ITransformerPlugin {
  /**
   * A unique name for the plugin. Used for error reporting and debugging.
   */
  readonly name: string;

  /**
   * A function that initializes the plugin. This is called once when the plugin is registered and can be used to set up any necessary state or configuration for the plugin.
   */
  init(): void;

  /**
   * A function that determines if the plugin should be applied to a given GraphQL definition.
   * @param definition - The GraphQL definition to check.
   * @returns `true` if the plugin should be applied, `false` otherwise.
   */
  match(definition: unknown): boolean;

  /**
   * An optional function that performs normalization transformations on the GraphQL document.
   * This is called before any execution transformations and can be used to prepare the document
   * for subsequent plugins.
   * @param definition - The GraphQL definition to transform.
   */
  normalize?(definition: unknown): void;

  /**
   * An optional function that performs execution transformations on the GraphQL document.
   * This is called after all normalization transformations have been applied and can be used
   * to perform final modifications to the document before it is finalized.
   * @param definition - The GraphQL definition to transform.
   */
  execute?(definition: unknown): void;

  /**
   * An optional function that performs cleanup operations on the GraphQL document after all
   * transformations have been applied. This can be used to remove any temporary fields or
   * directives added during normalization or execution.
   * @param definition - The GraphQL definition to clean up.
   */
  cleanup?(definition: unknown): void;

  /**
   * An optional function that generates output artifacts based on the transformed GraphQL document.
   * This can be used to contribute to the final output object, which includes the transformed schema
   * and any additional artifacts generated by the plugins.
   * @returns An object containing the output artifacts generated by the plugin.
   */
  output?(): Record<string, unknown>;
}
