import { ITransformerContext } from "../context/ITransformerContext.js";
import { DefinitionNode } from "../definition/index.js";

export interface ITransformerPlugin {
  /**
   * A unique name for the plugin. Used for error reporting and debugging.
   */
  readonly name: string;
  readonly context: ITransformerContext;

  /**
   * A function that initializes the plugin. This is called once when the plugin is registered and can be used to set up any necessary state or configuration for the plugin.
   */
  init(): void;

  /**
   * A function that is called before any transformations are applied. This can be used to perform any necessary setup or initialization before the transformation process begins.
   */

  before?(): void;

  /**
   * A function that is called after all transformations have been applied. This can be used to perform any necessary cleanup or finalization after the transformation process is complete.
   */
  after?(): void;

  /**
   * A function that determines if the plugin should be applied to a given GraphQL definition.
   * @param definition - The GraphQL definition to check.
   * @returns `true` if the plugin should be applied, `false` otherwise.
   */
  match(definition: DefinitionNode): boolean;

  /**
   * An optional function that performs normalization transformations on the GraphQL document.
   * This is called before any execution transformations and can be used to prepare the document
   * for subsequent plugins.
   * @param {DefinitionNode} definition - The GraphQL definition to transform.
   */
  normalize?(definition: DefinitionNode): void;

  /**
   * An optional function that performs execution transformations on the GraphQL document.
   * This is called after all normalization transformations have been applied and can be used
   * to perform final modifications to the document before it is finalized.
   * @param {DefinitionNode} definition - The GraphQL definition to transform.
   */
  execute?(definition: DefinitionNode): void;

  /**
   * An optional function that generates output artifacts based on the transformed GraphQL document.
   * This is called after all transformations have been applied and can be used to contribute to the final output object, which includes the transformed schema and any additional artifacts generated by the plugins.
   * @param {DefinitionNode} definition - The GraphQL definition to generate output for.
   */

  generate?(definition: DefinitionNode): void;

  /**
   * An optional function that performs cleanup operations on the GraphQL document after all
   * transformations have been applied. This can be used to remove any temporary fields or
   * directives added during normalization or execution.
   * @param {DefinitionNode} definition - The GraphQL definition to clean up.
   */
  cleanup?(definition: DefinitionNode): void;

  /**
   * An optional function that generates output artifacts based on the transformed GraphQL document.
   * This can be used to contribute to the final output object, which includes the transformed schema
   * and any additional artifacts generated by the plugins.
   * @returns An object containing the output artifacts generated by the plugin.
   */
  output?(): Record<string, unknown> | undefined;
}
