import { Source } from "graphql";
// Import the rules from the same module paths as validateSDL (DocumentNode), so rule identities match.
import { specifiedSDLRules } from "graphql/validation/specifiedRules.js";
import { KnownTypeNamesRule } from "graphql/validation/rules/KnownTypeNamesRule.js";
import { TransformerValidationError } from "@gqlbase/shared/errors";
import type { FileArtifact, ITransformerContext } from "../context/index.js";
import { DocumentNode } from "../definition/DocumentNode.js";

export interface TransformerOutput {
  schema: string;
  files: FileArtifact[];
  [key: string]: unknown;
}

/**
 * GraphQLTransformer is the main interface, responsible for transforming a GraphQL schema document and generating artifacts based on the provided plugins.
 *
 * The transformation process consists of several stages:
 * 1. **Initialization**: Each plugin is initialized with the transformation context.
 * 2. **Validation**: The schema document is validated for any errors. If validation fails, a `TransformerValidationError` is thrown. Unknown type names are not checked yet: the source may reference types that plugins generate, such as `StringFilterInput`. The whole document is validated again once `execute` has run, and once more at the end.
 * 3. **Normalization**: Each plugin that matches a definition can perform normalization on the definition. This stage is used to prepare the schema for transformation, such as adding necessary fields or directives.
 * 4. **Execution**: Each plugin that matches a definition executes its main transformation logic on the definition. This is where the core transformations happen, such as generating new types or modifying existing ones.
 * 5. **Cleanup**: Each plugin that matches a definition can perform cleanup operations on the definition. This stage is used to remove any temporary fields or directives added during normalization or execution.
 * 6. **Finalization**: After all definitions have been processed, each plugin can perform finalization tasks, such as cleaning up internal declarations or preparing for output generation.
 * 7. **Output Generation**: Each plugin that has an output method can contribute to the final output object, which includes the transformed schema and any additional artifacts generated by the plugins.
 *
 * The final output of the transformation process is an object containing the transformed schema and any additional artifacts generated by the plugins.
 */

const SOURCE_RULES = specifiedSDLRules.filter((rule) => rule !== KnownTypeNamesRule);

export class GraphQLTransformer {
  private readonly _context: ITransformerContext;

  constructor(context: ITransformerContext) {
    this._context = context;
  }

  public transform(source: string | Source): TransformerOutput {
    this._context.logger.debug("Starting transformation process...");
    const startTime = performance.now();

    const document = this._context.startWork(DocumentNode.fromSource(source));

    // The source may reference generated types, which do not exist yet: check type names after execute.
    const errors = document.validate(SOURCE_RULES);

    if (errors.length) {
      throw new TransformerValidationError(errors);
    }

    const validateStamp = performance.now();
    this._context.logger.debug(
      `Validation completed in ${(validateStamp - startTime).toFixed(2)}ms.`
    );

    this._context.logger.debug(`Document contains ${document.definitions.size} definitions.`);

    for (const plugin of this._context.plugins) {
      if (typeof plugin.before === "function") {
        plugin.before();
      }
    }

    const beforeStamp = performance.now();
    this._context.logger.debug(
      "Before phase completed. Time taken: " + (beforeStamp - validateStamp).toFixed(2) + "ms"
    );
    this._context.logger.debug("Starting normalization phase...");

    for (const definition of document.definitions.values()) {
      for (const plugin of this._context.plugins) {
        if (plugin.match(definition) && typeof plugin.normalize === "function") {
          plugin.normalize(definition);
        }
      }
    }

    const normalizeStamp = performance.now();
    this._context.logger.debug(
      `Normalization phase completed. Time taken: ${(normalizeStamp - beforeStamp).toFixed(2)}ms.`
    );

    this._context.logger.debug("Starting execution phase...");

    for (const definition of document.definitions.values()) {
      for (const plugin of this._context.plugins) {
        if (plugin.match(definition) && typeof plugin.execute === "function") {
          plugin.execute(definition);
        }
      }
    }

    const executeStamp = performance.now();
    this._context.logger.debug(
      `Execution phase completed. Time taken: ${(executeStamp - normalizeStamp).toFixed(2)}ms.`
    );

    // Every type now exists, so the full rules apply. Generators always see a valid document.
    const executedErrors = document.validate();

    if (executedErrors.length) {
      throw new TransformerValidationError(executedErrors);
    }

    for (const definition of document.definitions.values()) {
      for (const plugin of this._context.plugins) {
        if (plugin.match(definition) && typeof plugin.generate === "function") {
          plugin.generate(definition);
        }
      }
    }

    for (const definition of document.definitions.values()) {
      for (const plugin of this._context.plugins) {
        if (plugin.match(definition) && typeof plugin.cleanup === "function") {
          plugin.cleanup(definition);
        }
      }
    }

    for (const plugin of this._context.plugins) {
      if (typeof plugin.after === "function") {
        plugin.after();
      }
    }

    // A plugin that leaves invalid SDL behind (a directive usage without its definition, a dangling type) fails here.
    const outputErrors = document.validate();

    if (outputErrors.length) {
      throw new TransformerValidationError(outputErrors);
    }

    const output = {
      schema: document.print(),
      files: [],
    } as TransformerOutput;

    for (const plugin of this._context.plugins) {
      if (typeof plugin.output === "function") {
        Object.assign(output, plugin.output());
      }
    }

    output.files = this._context.files;

    this._context.finishWork();
    return output;
  }
}
