import { performance } from "node:perf_hooks";
import { Source } from "graphql";
import { Logger } from "@gqlbase/shared/logger";
import { TransformerValidationError } from "@gqlbase/shared/errors";
import type { ITransformerContext } from "../context/ITransformerContext.js";
import { DocumentNode } from "../definition/DocumentNode.js";

export interface GraphQLTransformerOptions {
  logger: Logger;
  throwOnError?: boolean;
}

export interface TransformerOutput {
  [key: string]: unknown;
  schema: string;
}

/**
 * GraphQLTransformer is the main interface, responsible for transforming a GraphQL schema document and generating artifacts based on the provided plugins.
 *
 * The transformation process consists of several stages:
 * 1. **Initialization**: Each plugin is initialized with the transformation context.
 * 2. **Validation**: The schema document is validated for any errors. If validation fails, a `TransformerValidationError` is thrown.
 * 3. **Normalization**: Each plugin that matches a definition can perform normalization on the definition. This stage is used to prepare the schema for transformation, such as adding necessary fields or directives.
 * 4. **Execution**: Each plugin that matches a definition executes its main transformation logic on the definition. This is where the core transformations happen, such as generating new types or modifying existing ones.
 * 5. **Cleanup**: Each plugin that matches a definition can perform cleanup operations on the definition. This stage is used to remove any temporary fields or directives added during normalization or execution.
 * 6. **Finalization**: After all definitions have been processed, each plugin can perform finalization tasks, such as cleaning up internal declarations or preparing for output generation.
 * 7. **Output Generation**: Each plugin that has an output method can contribute to the final output object, which includes the transformed schema and any additional artifacts generated by the plugins.
 *
 * The final output of the transformation process is an object containing the transformed schema and any additional artifacts generated by the plugins.
 */

export class GraphQLTransformer {
  private readonly _context: ITransformerContext;
  private readonly _logger: Logger;
  private readonly _options: GraphQLTransformerOptions;

  constructor(context: ITransformerContext, options: GraphQLTransformerOptions) {
    this._context = context;
    this._logger = options.logger;
    this._options = options;
  }

  public transform(source: string | Source): TransformerOutput {
    try {
      const startTime = performance.now();
      this._logger.debug("Starting transformation process...");
      const document = this._context.startWork(DocumentNode.fromSource(source));

      const errors = document.validate();

      if (errors.length) {
        throw new TransformerValidationError(errors);
      }

      this._logger.debug(
        `Validation completed in ${(performance.now() - startTime).toFixed(2)}ms.`
      );

      this._logger.debug(`Document contains ${document.definitions.size} definitions.`);

      for (const plugin of this._context.plugins) {
        if (typeof plugin.before === "function") {
          plugin.before();
        }
      }

      this._logger.debug("Starting normalization phase...");

      for (const definition of document.definitions.values()) {
        for (const plugin of this._context.plugins) {
          if (plugin.match(definition) && typeof plugin.normalize === "function") {
            plugin.normalize(definition);
          }
        }
      }

      this._logger.debug(
        `Normalization phase completed in ${(performance.now() - startTime).toFixed(2)}ms.`
      );

      this._logger.debug("Starting execution phase...");

      for (const definition of document.definitions.values()) {
        for (const plugin of this._context.plugins) {
          if (plugin.match(definition) && typeof plugin.execute === "function") {
            plugin.execute(definition);
          }
        }
      }

      this._logger.debug(
        `Execution phase completed in ${(performance.now() - startTime).toFixed(2)}ms.`
      );

      for (const definition of document.definitions.values()) {
        for (const plugin of this._context.plugins) {
          if (plugin.match(definition) && typeof plugin.cleanup === "function") {
            plugin.cleanup(definition);
          }
        }
      }

      for (const plugin of this._context.plugins) {
        if (typeof plugin.after === "function") {
          plugin.after();
        }
      }

      for (const plugin of this._context.plugins) {
        if (typeof plugin.generate === "function") {
          plugin.generate();
        }
      }

      const output = {
        schema: document.print(),
      };

      for (const plugin of this._context.plugins) {
        if (typeof plugin.output === "function") {
          Object.assign(output, plugin.output());
        }
      }

      this._context.finishWork();
      return output;
    } catch (error) {
      this._context.finishWork();

      if (this._options.throwOnError) {
        throw error;
      } else {
        this._logger.error(error instanceof Error ? error.stack || error.message : String(error));
        return { schema: "" };
      }
    }
  }
}
